# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 95caa04e09d50d2d6920030e6133532275586c6cf80e53b2438e6beb334e7da512519a8c284d429f2a5d474b604dacd4a464911db12ac6844967d09c2d65604a

test:
  secret_key_base: 5f5dbf183194ea10730c3c13d1572b0845d3c4c7d7362006150f855982049300e6f1af99b75f187c53578891e15cdd72a8be645e4beb0922adb78472ec7be3dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
